version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    env_file:
      - edge-variables.env
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
    command: mosquitto -c /mosquitto-no-auth.conf
  sparkmaster: 
    image: mahsahadian/spark-master
    container_name: sparkmaster
    restart: always
    env_file:
      - edge-variables.env
    ports:
      - "8080:8080"
      - "7077:7077"
  sparkworker: 
    image: mahsahadian/spark-worker
    container_name: sparkworker
    restart: always
    depends_on:
      - sparkmaster
    env_file:
      - edge-variables.env
  sparkjob: 
    image: mahsahadian/spark-job
    container_name: sparkjob
    restart: always
    depends_on:
      - sparkworker
    env_file:
      - edge-variables.env
